name: My First Workflow
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from Step 1"
      - name: Step 2
        run: echo "Hello from Step 2"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "Hello from Step 3"
      - name: Step 4
        run: echo "Hello from Step 4"
